### ISSUE TITLE
Solver Results

### ISSUE THREAD

**Issue by dev-ns8** [bupticybee/TexasHoldemSolverJava#23]
So from my understanding, after the solver completes a solve, it writes the results to a file.  This file is then interpreted by some SolverResult class. 

So my question is, is there any way to save these files and then re-import them into the SolverResult GUI to view the already solved scenario without re-running the sim? 

Also where are these result files saved?  Are they saved somewhere in the test/ directory?

Thanks for all your work.

**Comment by bupticybee** [comment]
Actually your understanding is wrong. 

After the solver completes a solve, it didn't write the result to file, at least it's not what happened in the gui version. After solving, the solver keeps the result in memory and access them through memory. Currently sadly there is no way to re-import the result to the gui, but I will put this to schedule.

ps: This java solver will be abandoned soon，because new c++ version's gui is under development https://github.com/bupticybee/TexasSolver , I will try implement re-import in c++ version. 

Thank you for your feedbacks.

**Comment by dev-ns8** [comment]
Understood. Excited about the c++ version! What are you writing the GUI in? QT?

**Comment by bupticybee** [comment]
Closing because this issue is solved.
